/*
 * Hebrew Wake Word Model Data Header
 *
 * This file contains the TensorFlow Lite Micro model data for Hebrew wake word detection.
 * The model data is stored as a C array and should be generated by the model conversion script.
 *
 * Generated from: hebrew_wake_word_model_int8.tflite
 */

#ifndef TENSORFLOW_LITE_MICRO_EXAMPLES_HEBREW_WAKE_WORD_MODEL_DATA_H_
#define TENSORFLOW_LITE_MICRO_EXAMPLES_HEBREW_WAKE_WORD_MODEL_DATA_H_

#include <cstdint>

extern const unsigned char g_hebrew_wake_word_model_data[];
extern const unsigned int g_hebrew_wake_word_model_data_len;

#endif  // TENSORFLOW_LITE_MICRO_EXAMPLES_HEBREW_WAKE_WORD_MODEL_DATA_H_
